apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: cloud-deploy-test
description: cloud deploy delivery pipeline
serialPipeline:
 stages:
 - targetId: dev
 - targetId: test
 - targetId: prod

---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: dev
description: dev cluster
requireApproval: true
gke:
  cluster: projects/cloudcomputing-348415/locations/asia-east1/clusters/cluster-dev

---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: prod
description: prod cluster
requireApproval: true
gke:
  cluster: projects/cloudcomputing-348415/locations/us-east1/clusters/cluster-prod

---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: test
description: test cluster
requireApproval: true
gke:
  cluster: projects/cloudcomputing-348415/locations/us-east1/clusters/cluster-test

---